version: '3.8'

services:
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  users-service:
    build: ./users-service
    ports:
      - "8000:8000"
    depends_on:
      - mongo

volumes:
  mongo-data:
